version: "3.7"

services: 

    httpd:
        build:
            context: ./apache_src/
            dockerfile: ./Dockerfile
        image: myapache
        container_name: apache-server
        hostname: apache-server
        ports: 
            - "80:80"
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat1:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile1
        image: mytomcat:tomcat1
        container_name: tomcat-server1
        hostname: tomcat-server1
        ports: 
            - "8080:8080"
            - "8009:8009"  # for sync with apache
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat2:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile2
        image: mytomcat:tomcat2
        container_name: tomcat-server2
        hostname: tomcat-server2
        # depends_on:
        #     - tomcat1
        ports: # May be need to erase 
            - "8180:8080"
            - "8109:8009"  # for sync with apache
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"
