version: "3"

services: 

    httpd:
        build:
            context: ./apache_src/
            dockerfile: ./Dockerfile
        image: myapache
        container_name: apache-server
        ports: 
            - "80:80"
        logging: 
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "10m"

    tomcat1:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile2
        image: mytomcat
        hostname: node1
        container_name: tomcat-server1
        command: 
            - bash
            - -c
            - |
              sed -i "s/WORKER_NAME/node1/g" /usr/local/tomcat/conf/server.xml
              /usr/local/tomcat/bin/catalina.sh run
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat2:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile2
        image: mytomcat
        hostname: node2
        container_name: tomcat-server2
        command: 
            - bash
            - -c
            - |
              sed -i "s/WORKER_NAME/node2/g" /usr/local/tomcat/conf/server.xml
              /usr/local/tomcat/bin/catalina.sh run
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"
