version: "3"

services: 

    httpd:
        build:
            context: ./apache_src/
            dockerfile: ./Dockerfile
        image: myapache
        container_name: apache-server
        ports: 
            - "80:80"
        logging: 
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "10m"

    tomcat1:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile2
        image: mytomcat
        hostname: node1
        container_name: tomcat-node1
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat2:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile2
        image: mytomcat
        hostname: node2
        container_name: tomcat-node2
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"
