version: "3"

services: 
    httpd:
        build:
            context: ./apache_src/
            dockerfile: ./Dockerfile
        image: httpd:2.4
        container_name: apache-server
        ports: 
            - "55891:80"
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat1:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile
        image: tomcat:9.0
        container_name: tomcat-server1
        ports: 
            - "55991:8080"
            - "55901:8009"  # for sync with apache
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat2:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile
        image: tomcat:9.0
        container_name: tomcat-server2
        ports: 
            - "55992:8080"
            - "55902:8009"  # for sync with apache
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"