version: "3"

services: 
    httpd:
        image: httpd:2.4
        build: ./apache_src/
        ports: 
            - "55891:80"
        volumes: 
            - ./webcontents/:/usr/local/apache2/htdocs/ #local changes directly apply
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat1:
        image: tomcat:9.0
        build: ./tomcat_src/
        ports: 
            - "55991:8080"
            - "55901:8009"  # for sync with apache
        volumes: 
            - ./tomcat_src/src/:/usr/local/tomcat/webapps/ROOT
        # command: 
            # - /usr/local/tomcat/bin/catalina.sh up    # default
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat2:
        image: tomcat:9.0
        build: ./tomcat_src/
        ports: 
            - "55992:8080"
            - "55902:8009"  # for sync with apache
        volumes: 
            - ./tomcat_src/src/:/usr/local/tomcat/webapps/ROOT
        # command: 
            # - /usr/local/tomcat/bin/catalina.sh up    # default
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"